/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CityHead;

import Business.Comparison.Comparison;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Order.Order;
import Business.Order.StoreOrder;
import Business.Organization.Organization;
import Business.Organization.StoreAdminOrganization;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prasad
 */
public class StoreOrderSection extends javax.swing.JPanel {

    /**
     * Creates new form StoreOrderSection
     */
    JPanel userProcessContainer;
    Network network;
    UserAccount account;

    StoreOrderSection(JPanel userProcessContainer, Network network, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.account = account;
        
        storeComboBox.removeAllItems();
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
              storeComboBox.addItem(enterprise);
           }
    }

    
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        storeComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingOrderTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        approveOrderButton = new javax.swing.JButton();
        searchedProductTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Stores Section");

        storeComboBox.setBackground(new java.awt.Color(204, 255, 153));
        storeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        storeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Select Store");

        pendingOrderTable.setBackground(new java.awt.Color(204, 255, 153));
        pendingOrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Number", "Order Date & Time"
            }
        ));
        jScrollPane1.setViewportView(pendingOrderTable);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Pending Orders");

        approveOrderButton.setText("Approve Order");
        approveOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveOrderButtonActionPerformed(evt);
            }
        });

        searchedProductTextField.setBackground(new java.awt.Color(204, 255, 255));
        searchedProductTextField.setEnabled(false);

        jLabel4.setText("Top Product  by Customer Search Results");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(storeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 267, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(approveOrderButton)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37)
                        .addComponent(searchedProductTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(305, 305, 305))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(approveOrderButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchedProductTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(112, 112, 112))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void storeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeComboBoxActionPerformed
        // TODO add your handling code here:
        Enterprise enterprise = (Enterprise) storeComboBox.getSelectedItem();
        
        if(enterprise!=null)
        {
        DefaultTableModel model = (DefaultTableModel) pendingOrderTable.getModel();

        model.setRowCount(0);
        
        if(!enterprise.getStoreOrderDirectory().getOrderList().isEmpty())
        {    
        for (Order s : enterprise.getStoreOrderDirectory().getOrderList())
          {
            StoreOrder so = (StoreOrder) s;
            if(so.isCityAheadApproval()==false)
            {
              
                Object row[] = new Object[2];
                row[0] = so.getSorderNumber();
                row[1] = s;
                
                model.addRow(row);
            }  
                      
          }   
        }
        ArrayList<Comparison> cmp1 = new ArrayList<>();
         
         for(Product p: enterprise.getProductCatalog().getProductList())
         {
              Comparison c = new Comparison(p.getName(),p.getSearchCount());
               cmp1.add(c);
         }   
        
         Collections.sort(cmp1);
         
         searchedProductTextField.setText(cmp1.get(0).getString());
        
        } 
    }//GEN-LAST:event_storeComboBoxActionPerformed

    private void approveOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveOrderButtonActionPerformed
        // TODO add your handling code here:
        
          int selectedRow = pendingOrderTable.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please Select a Order first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        else
        {  
          Order order = (Order) pendingOrderTable.getValueAt(selectedRow, 1);
          StoreOrder so = (StoreOrder) order;
          if(so.isCityAheadApproval()==false)
          {  
              JOptionPane.showMessageDialog(null,"Order has been already approved", "Message", JOptionPane.INFORMATION_MESSAGE);
              return;
          }  
          else
          {   
           so.setCityAheadApproval(true);
           JOptionPane.showMessageDialog(null,"Order has been sent to Supplier", "Message", JOptionPane.INFORMATION_MESSAGE);
          }       
                
         }
        
          
    }//GEN-LAST:event_approveOrderButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveOrderButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pendingOrderTable;
    private javax.swing.JTextField searchedProductTextField;
    private javax.swing.JComboBox storeComboBox;
    // End of variables declaration//GEN-END:variables
}
