/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.StoreAdmin;

import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Prasad
 */
public class StoreAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form StoreAdminWorkArea
     */
   JPanel userProcessContainer;
   Enterprise enterprise;

    public StoreAdminWorkArea(JPanel userProcessContainer, Enterprise enterprise) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.enterprise = enterprise;
       
       cityNameLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageUsersButton = new javax.swing.JButton();
        manageOrganizationsButton = new javax.swing.JButton();
        cityNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        manageUsersButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageUsersButton.setText("Manage Users");
        manageUsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUsersButtonActionPerformed(evt);
            }
        });

        manageOrganizationsButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageOrganizationsButton.setText("Manage Organizations");
        manageOrganizationsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationsButtonActionPerformed(evt);
            }
        });

        cityNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cityNameLabel.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Store Admin Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(cityNameLabel)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addContainerGap(249, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageOrganizationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(293, 293, 293))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityNameLabel)
                    .addComponent(jLabel2))
                .addGap(92, 92, 92)
                .addComponent(manageOrganizationsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(manageUsersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {manageOrganizationsButton, manageUsersButton});

    }// </editor-fold>//GEN-END:initComponents

    private void manageUsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUsersButtonActionPerformed
        // TODO add your handling code here:
        ManageUsers msk = new ManageUsers(userProcessContainer, enterprise);
        userProcessContainer.add("ManageStoreKeeper", msk);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUsersButtonActionPerformed

    private void manageOrganizationsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationsButtonActionPerformed
        // TODO add your handling code here:
        ManageOrganizations mo = new ManageOrganizations(userProcessContainer, enterprise);
        userProcessContainer.add("ManageOrganizations", mo);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cityNameLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageOrganizationsButton;
    private javax.swing.JButton manageUsersButton;
    // End of variables declaration//GEN-END:variables
}
