/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NetworkAdmin;

import Business.Employee.Employee;
import Business.Network.Network;
import Business.Organization.CityHeadOrganization;
import Business.Organization.Organization;
import Business.Role.CityHeadRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prasad
 */
public class ManageCityHead extends javax.swing.JPanel {

    /**
     * Creates new form ManageCityHead
     */
    JPanel userProcessContainer;
    Network network;

    ManageCityHead(JPanel userProcessContainer, Network network) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.network = network;
       
       cityNameLabel.setText(network.getNetworkName());
       populateTable();
    }
private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) cityHeadTable.getModel();

        model.setRowCount(0);
        
         
            for (Organization org : network.getOrganizationDirectory().getOrganizationList())
            {
                
                      if(org instanceof CityHeadOrganization)
                      {
                         for (UserAccount userAccount : org.getUserAccountDirectory().getUserAccountList())
                         {
                         Object[] row = new Object[2];
                         row[0] = userAccount.getEmployee();
                         row[1] = userAccount.getUsername();

                         model.addRow(row); 
                      }
                
                }
            }
        
        
   }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        cityHeadTable = new javax.swing.JTable();
        headerLabel = new javax.swing.JLabel();
        sideHeaderLabel = new javax.swing.JLabel();
        cityNameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        userNameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        createButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setBackground(java.awt.Color.white);

        cityHeadTable.setBackground(new java.awt.Color(204, 255, 153));
        cityHeadTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CityHead Name", "CityHead UserName"
            }
        ));
        jScrollPane1.setViewportView(cityHeadTable);

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        headerLabel.setText("CityHead Creation");

        sideHeaderLabel.setText("City");

        cityNameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cityNameLabel.setText("jLabel3");

        nameLabel.setText("Name");

        userNameLabel.setText("UserName");

        passwordLabel.setText("Password");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sideHeaderLabel)
                        .addGap(18, 18, 18)
                        .addComponent(cityNameLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addComponent(userNameLabel)
                                    .addComponent(passwordLabel))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTextField)
                                    .addComponent(userNameTextField)
                                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(createButton)
                                .addGap(122, 122, 122)))
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(headerLabel)
                        .addGap(256, 256, 256))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerLabel)
                    .addComponent(sideHeaderLabel)
                    .addComponent(cityNameLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(backButton))
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        Organization org= null;
        int x=0;
        if (nameTextField.getText().trim().matches("") || userNameTextField.getText().trim().matches("") || String.valueOf(passwordField.getPassword()).trim().matches("") )
        {  
          JOptionPane.showMessageDialog(null, "All fields are mandatory!!!", "Warning", JOptionPane.WARNING_MESSAGE);  
        } 
        else
        {    
        
         for(Organization o:network.getOrganizationDirectory().getOrganizationList())
         {
             if(o instanceof CityHeadOrganization)
             {
                 org=o;
                 x=0;
                 break;
             }
             else
             {
                 x=1;
             }
         }  
         
         if(x==1)
         {    
         org = network.getOrganizationDirectory().createOrganization(Organization.Type.CityHead);
         }
         
         if(org.getUserAccountDirectory().checkIfUsernameIsUnique(userNameTextField.getText())==false)
         {  
           JOptionPane.showMessageDialog(null, "This Username already exists. Please try with some other username!!!", "Warning", JOptionPane.WARNING_MESSAGE);
         }
         else
         {    
         Employee employee = org.getEmployeeDirectory().createEmployee(nameTextField.getText());
        org.getUserAccountDirectory().createUserAccount(userNameTextField.getText(),String.valueOf(passwordField.getPassword()), employee, new CityHeadRole());
        JOptionPane.showMessageDialog(null, "City Head has been created!!!", "Information", JOptionPane.INFORMATION_MESSAGE);
        populateTable();
        nameTextField.setText("");
        userNameTextField.setText("");
        passwordField.setText("");
        }
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable cityHeadTable;
    private javax.swing.JLabel cityNameLabel;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel sideHeaderLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
