/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NetworkAdmin;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Product.InitializeProductClasses;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prasad
 */
public class ManageStore extends javax.swing.JPanel {

    /**
     * Creates new form EnterpriseCreation
     */
   JPanel userProcessContainer;
   Network network;
   InitializeProductClasses ipc;
   
    ManageStore(JPanel userProcessContainer, Network network) {
        initComponents();
        this.userProcessContainer= userProcessContainer;
        this.network = network;
        ipc = new InitializeProductClasses();
        
        cityNameLabel.setText(network.getNetworkName());
        populateTable();
               
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) storeTable.getModel();

        model.setRowCount(0);
        
         
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList())
            {
                                   
                        Object[] row = new Object[2];
                         row[0] = e.getId();
                         row[1] = e;
                         model.addRow(row); 
                      
                        
            }
        
        
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        storeTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cityNameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        addStoreButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setBackground(java.awt.Color.white);

        headerLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        headerLabel.setText("Store Creation");

        storeTable.setBackground(new java.awt.Color(204, 255, 153));
        storeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Store ID", "Store Name"
            }
        ));
        jScrollPane1.setViewportView(storeTable);

        jLabel1.setText("City :");

        cityNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cityNameLabel.setText("jLabel2");

        jLabel2.setText("Name");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        addStoreButton.setText("Add Store");
        addStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStoreButtonActionPerformed(evt);
            }
        });

        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cityNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel)
                .addGap(273, 273, 273))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(backButton)
                .addContainerGap(695, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addStoreButton)
                        .addGap(290, 290, 290))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(72, 72, 72)
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerLabel)
                    .addComponent(jLabel1)
                    .addComponent(cityNameLabel))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(addStoreButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void addStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStoreButtonActionPerformed
        // TODO add your handling code here:
        int x = 0;
        if(nameTextField.getText().trim().matches(""))
        {
        JOptionPane.showMessageDialog(null, "This field is mandatory!!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        else
        {   
            
         if(network.getEnterpriseDirectory().getEnterpriseList().isEmpty()==false)
        {   
            for (Enterprise e: network.getEnterpriseDirectory().getEnterpriseList())
            {
                if(e.getName().matches(nameTextField.getText()))
                {
                  JOptionPane.showMessageDialog(null, "This Store already exists. Please use some other name...!!", "Warning", JOptionPane.WARNING_MESSAGE); 
                  x=0;
                  break;
                }  
                else
                {
                    x=1;
                }    
            }
        }
        else
         {
             x=1;
         } 
         
         if(x==1)
         {     
        Enterprise e = network.getEnterpriseDirectory().createAndAddEnterprise(nameTextField.getText(), Enterprise.EnterpriseType.Retail);
        
        e.setId(network.getEnterpriseDirectory().getEnterpriseList().size());
        e.setProductCatalog(ipc.getProductlist());
        e.setShelfDirectory(ipc.getShelfDirectory());
        JOptionPane.showMessageDialog(null, "Store has been Created!!!", "Information", JOptionPane.INFORMATION_MESSAGE);
        nameTextField.setText("");
        populateTable();
        }
       }    
    }//GEN-LAST:event_addStoreButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStoreButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel cityNameLabel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTable storeTable;
    // End of variables declaration//GEN-END:variables
}
