/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NetworkAdmin;

import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Prasad
 */
public class NetworkAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form NetworkAdminWorkArea
     */
   
    JPanel userProcessContainer;
    Network network;
   
    public NetworkAdminWorkArea(JPanel userProcessContainer, Network network) {
      initComponents();
      this.userProcessContainer = userProcessContainer;
      this.network = network;
      
      cityNameLabel.setText(network.getNetworkName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageStoreButton = new javax.swing.JButton();
        storeAdminButton = new javax.swing.JButton();
        manageCityHeadButton = new javax.swing.JButton();
        cityNameLabel = new javax.swing.JLabel();
        otherHeaderLabel = new javax.swing.JLabel();

        setBackground(java.awt.Color.white);

        manageStoreButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageStoreButton.setText("Manage Stores");
        manageStoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageStoreButtonActionPerformed(evt);
            }
        });

        storeAdminButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        storeAdminButton.setText("Manage Store Admin");
        storeAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeAdminButtonActionPerformed(evt);
            }
        });

        manageCityHeadButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageCityHeadButton.setText("Manage CityHead");
        manageCityHeadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCityHeadButtonActionPerformed(evt);
            }
        });

        cityNameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cityNameLabel.setText("jLabel1");

        otherHeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        otherHeaderLabel.setText("City Admin Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(cityNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(otherHeaderLabel)
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(storeAdminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageStoreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageCityHeadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(279, 279, 279))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityNameLabel)
                    .addComponent(otherHeaderLabel))
                .addGap(82, 82, 82)
                .addComponent(manageCityHeadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(manageStoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(storeAdminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageStoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageStoreButtonActionPerformed
        // TODO add your handling code here:
        ManageStore sc = new ManageStore(userProcessContainer, network);
        userProcessContainer.add("StoreCreation", sc);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageStoreButtonActionPerformed

    private void manageCityHeadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCityHeadButtonActionPerformed
        // TODO add your handling code here:
        ManageCityHead chc = new ManageCityHead(userProcessContainer, network);
        userProcessContainer.add("CityHeadCreation", chc);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCityHeadButtonActionPerformed

    private void storeAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeAdminButtonActionPerformed
        // TODO add your handling code here:
        ManageStoreAdmin sac = new ManageStoreAdmin(userProcessContainer, network);
        userProcessContainer.add("StoreAdminCreation", sac);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_storeAdminButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cityNameLabel;
    private javax.swing.JButton manageCityHeadButton;
    private javax.swing.JButton manageStoreButton;
    private javax.swing.JLabel otherHeaderLabel;
    private javax.swing.JButton storeAdminButton;
    // End of variables declaration//GEN-END:variables
}
